### ISSUE TITLE
The number of video segments

### ISSUE THREAD

**Issue by MUVGuan** [DannyTran123/egopet#1]
Hi Danny, thank you and your team for such a great work!
After downloading this dataset, I count the number of segments in training and validation sets, which are 6126 and 510 respectively. But in the paper, it says that EgoPet has 6646 segments totally, which is not equal to the summation of 6126 and 510. I am not sure if I miss some videos when downloading the dataset, looking forward to your reply. Thanks!

**Comment by amirbar** [comment]
Hi @MUVGuan , thanks for the inquiry. The dataset you downloaded was the exact dataset we were using in the paper. The statistics in the text might have slightly predated it, and we will probably update them in the next version.

**Comment by MUVGuan** [comment]
Hi @amirbar , thank you very much for your timely response, looking forward to seeing the next version.
