### ISSUE TITLE
Where is the evaluation set in VPP task?

### ISSUE THREAD

**Issue by MUVGuan** [DannyTran123/egopet#2]
Hi @DannyTran123 @amirbar ,

Thanks for your great work!

In VPP task, you say that you have collected an evaluation dataset from Unitree A1 robot, the length is about 20 minutes. But I only find the training dataset from the file CMS_data.tar.gz (link: https://drive.google.com/file/d/1ZKSWwCoZP1mHjpksIEAwh3sTeeSJNF3B/view?usp=sharing), could you please tell me where is the evaluation dataset?

Thanks!

**Comment by amirbar** [comment]
Hi @MUVGuan,

CMS_data.tar.gz contains both training and testing data. The finetuning script automatically evaluates the resulting model performance during linear probing.

Amir

**Comment by MUVGuan** [comment]
Hi @amirbar ,

Thanks for your reply. So you mean CMS_data.tar.gz already contains the 20 minites evaluation dataset you collected, which is "test" file folder, right?

**Comment by amirbar** [comment]
yes!
